<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

  <!-- Root element -->
  <xs:element name="AxLabelFile" type="AxLabelFileType"/>

  <!-- AxLabelFile complex type -->
  <xs:complexType name="AxLabelFileType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="LabelContentFileName" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="LabelFileId" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="Language" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="RelativeUriInModelStore" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>